### ISSUE TITLE
Change DB column types

### ISSUE THREAD

**Issue by TrustedMercury** [teamcodebyte/haven-backend#32]
## Description

Change -
- the ``publicity`` column in ``user_details`` to ``public``, of ``BOOLEAN`` type
- ``status`` column in ``user_connection_requests`` to ``SMALLINT`` type
- Add a ``status`` column of type ``SMALLINT`` to ``user_reports`` column, after the ``proof`` column
- ``status`` column in ``user_email_verification`` to ``SMALLINT`` type
- ``status`` column in ``user_referrals`` to ``SMALLINT`` type
- Add ``bio`` column to ``user_identity`` of type ``TEXT``, before the ``description`` column

**Comment by clvrk** [comment]
I'll say that publicity should be turned into a boolean logically, everything else, well, I quite frankly don't know how the hell DB's work so couldn't really say.
